### ISSUE TITLE
Ferroelectric workflow tests fail

### ISSUE THREAD

**Issue by computron** [hackingmaterials/atomate#205]
@blondegeek 

Not sure exactly what is the problem, but when I run locally I get the following.

Note that CircleCI is not configured to run VASP integration tests correctly so we didn't catch this whenever it actually failed (that is literally a separate issue)

======================================================================
ERROR: test_wf (atomate.vasp.workflows.tests.test_ferroelectric_workflow.TestFerroelectricWorkflow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ajain/Documents/code_matgen/atomate/atomate/vasp/workflows/tests/test_ferroelectric_workflow.py", line 124, in test_wf
    self._check_run(d, "_polar_relaxation")
  File "/Users/ajain/Documents/code_matgen/atomate/atomate/vasp/workflows/tests/test_ferroelectric_workflow.py", line 86, in _check_run
    self.assertAlmostEqual(d["calcs_reversed"][0]["output"]["structure"]["lattice"]["c"], 4.2157, 2)
TypeError: 'NoneType' object is not subscriptable
-------------------- >> begin captured logging << --------------------
launchpad: DEBUG: RESTARTED fw_id, launch_id to (1, 1)
launchpad: INFO: Performing db tune-up
launchpad: DEBUG: Updating indices...
launchpad: INFO: LaunchPad was RESET.
launchpad: INFO: Added a workflow. id_map: {-221: 1, -219: 2, -217: 3, -215: 4, -214: 5}
launchpad: DEBUG: FW with id: 5 is unique!
rocket.launcher: INFO: Created new dir /Users/ajain/Documents/code_matgen/atomate/atomate/utils/scratch/launcher_2018-02-02-22-22-51-777535
rocket.launcher: INFO: Launching Rocket
launchpad: DEBUG: FW with id: 5 is unique!
launchpad: DEBUG: Created/updated Launch with launch_id: 1
launchpad: DEBUG: RUNNING FW with id: 5
rocket.launcher: INFO: RUNNING fw_id: 5 in directory: /Users/ajain/Documents/code_matgen/atomate/atomate/utils/scratch/launcher_2018-02-02-22-22-51-777535
rocket.launcher: INFO: Task started: {{atomate.vasp.firetasks.write_inputs.WriteVaspFromIOSet}}.
rocket.launcher: INFO: Task completed: {{atomate.vasp.firetasks.write_inputs.WriteVaspFromIOSet}} 
rocket.launcher: INFO: Task started: {{atomate.vasp.firetasks.run_calc.RunVaspFake}}.
rocket.launcher: INFO: Rocket finished
launchpad: DEBUG: FW with id: 4 is unique!
rocket.launcher: INFO: Created new dir /Users/ajain/Documents/code_matgen/atomate/atomate/utils/scratch/launcher_2018-02-02-22-22-51-851444
rocket.launcher: INFO: Launching Rocket
launchpad: DEBUG: FW with id: 4 is unique!
launchpad: DEBUG: Created/updated Launch with launch_id: 2
launchpad: DEBUG: RUNNING FW with id: 4
rocket.launcher: INFO: RUNNING fw_id: 4 in directory: /Users/ajain/Documents/code_matgen/atomate/atomate/utils/scratch/launcher_2018-02-02-22-22-51-851444
rocket.launcher: INFO: Task started: {{atomate.vasp.firetasks.write_inputs.WriteVaspFromIOSet}}.
rocket.launcher: INFO: Task completed: {{atomate.vasp.firetasks.write_inputs.WriteVaspFromIOSet}} 
rocket.launcher: INFO: Task started: {{atomate.vasp.firetasks.run_calc.RunVaspFake}}.
rocket.launcher: INFO: Rocket finished
launchpad: DEBUG: RESTARTED fw_id, launch_id to (1, 1)
launchpad: INFO: Performing db tune-up
launchpad: DEBUG: Updating indices...
launchpad: INFO: LaunchPad was RESET.

**Comment by blondegeek** [comment]
Thanks for the heads up. I will take a look at this in the next week.

**Comment by computron** [comment]
Hi @blondegeek 

Any updates on this unit test?

**Comment by ardunn** [comment]
I noticed that this got fixed when having a `~/.pmgrc.yaml` file containing the following:

```
PMG_VASP_PSP_DIR: /path/to/your/POTCARs
```

Only I am not sure which specific POTCARs got it working. Anyway hope this helps.
